// app
export const SELECT_MIDI_CONTROLLER = 'SELECT_MIDI_CONTROLLER';
export const SELECT_NUMBER_OF_KEYBOARD_OCTAVES =
  'SELECT_NUMBER_OF_KEYBOARD_OCTAVES';
export const SET_WEB_MIDI_SUPPORTED = 'SET_WEB_MIDI_SUPPORTED';
export const SELECT_CHORD_PROGRESSION = 'SELECT_CHORD_PROGRESSION';

// lesson
export const SELECT_TONIC = 'SELECT_TONIC';

// game
export const START_GAME = 'START_GAME';
export const NOTES_PRESSED = 'NOTES_PRESSED';
