export const SELECT_MIDI_CONTROLLER = 'SELECT_MIDI_CONTROLLER';
export const SELECT_NUMBER_OF_KEYBOARD_OCTAVES = 'SELECT_NUMBER_OF_KEYBOARD_OCTAVES';
export const SET_WEB_MIDI_SUPPORTED = 'SET_WEB_MIDI_SUPPORTED';
